### ISSUE TITLE
crash on OSX

### ISSUE THREAD

**Issue by tlightsky** [robvanmieghem/gominer#32]
os:OSX
version:10.13.2

```
➜  gominer -url stratum+tcp://us-east.siamining.com:3333 -user c284c35f27f78569ec4b4d0626bfa41450bce23113d32a25b9eaa96b886f392e38311f5a05c6.NOBODY
2017/12/31 21:20:53 Platform Apple
2017/12/31 21:20:53 2 device(s) found:
2017/12/31 21:20:53 0 - GPU - HD Graphics 4000
2017/12/31 21:20:53 1 - GPU - GeForce GT 650M
2017/12/31 21:20:53 Starting SIA mining
2017/12/31 21:20:53 1 - Initializing GPU - GeForce GT 650M
2017/12/31 21:20:53 0 - Initializing GPU - HD Graphics 4000
2017/12/31 21:20:53 Connecting to us-east.siamining.com:3333
2017/12/31 21:20:54 ERROR fetching work - No job received from stratum server yet
2017/12/31 21:20:54 Stratum server changed difficulty to 7.999877929687528
2017/12/31 21:20:54 New job received from stratum server
2017/12/31 21:20:54 Authorization of c284c35f27f78569ec4b4d0626bfa41450bce23113d32a25b9eaa96b886f392e38311f5a05c6.NOBODY : true
2017/12/31 21:20:55 0 - Global item size: 268435456 (Intensity 0 ) - Local item size: 512
2017/12/31 21:20:55 0 - Initialized  GPU - HD Graphics 4000
2017/12/31 21:20:55 1 - Global item size: 268435456 (Intensity 0 ) - Local item size: 1024
2017/12/31 21:20:55 1 - Initialized  GPU - GeForce GT 650M
SIGABRT: abort
PC=0x7fff6f107e3e m=5 sigcode=0
signal arrived during cgo execution

goroutine 20 [syscall, locked to thread]:
runtime.cgocall(0x4227190, 0xc420041718, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:131 +0xe2 fp=0xc4200416c8 sp=0xc420041688
github.com/robvanmieghem/go-opencl/cl._Cfunc_clEnqueueWriteBuffer(0x450d150, 0x470f320, 0xc400000001, 0x0, 0x50, 0xc4200904b0, 0xc400000000, 0x0, 0xc42008c098, 0x0)
	github.com/robvanmieghem/go-opencl/cl/_obj/_cgo_gotypes.go:672 +0x50 fp=0xc420041718 sp=0xc4200416c8
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueWriteBuffer.func1(0x450d150, 0x470f320, 0x1, 0x0, 0x50, 0xc4200904b0, 0xc400000000, 0x0, 0xc42008c098, 0xc400000000)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:99 +0x1ff fp=0xc420041788 sp=0xc420041718
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueWriteBuffer(0xc420014190, 0xc42013a030, 0xc420092201, 0x0, 0x50, 0xc4200904b0, 0x0, 0x0, 0x0, 0xc4200419e8, ...)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:99 +0xea fp=0xc420041810 sp=0xc420041788
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueWriteBufferByte(0xc420014190, 0xc42013a030, 0xc420041901, 0x0, 0xc4200904b0, 0x50, 0x50, 0x0, 0x0, 0x0, ...)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:106 +0x9c fp=0xc420041880 sp=0xc420041810
github.com/robvanmieghem/gominer/algorithms/sia.(*singleDeviceMiner).mine(0xc42007c600)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:173 +0x1348 fp=0xc420041fd8 sp=0xc420041880
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420041fe0 sp=0xc420041fd8
created by github.com/robvanmieghem/gominer/algorithms/sia.(*Miner).Mine
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:56 +0x1ea

goroutine 1 [chan receive]:
main.main()
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/main.go:97 +0xd87

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan send]:
github.com/robvanmieghem/gominer/algorithms/sia.(*Miner).createWork(0xc42007c5c0)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:99 +0x26c
created by github.com/robvanmieghem/gominer/algorithms/sia.(*Miner).Mine
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:46 +0x9b

goroutine 21 [syscall, locked to thread]:
github.com/robvanmieghem/go-opencl/cl._Cfunc_clEnqueueReadBuffer(0x46373b0, 0x4756960, 0xc400000001, 0x0, 0x8, 0xc420075a40, 0xc400000000, 0x0, 0xc42008c088, 0x0)
	github.com/robvanmieghem/go-opencl/cl/_obj/_cgo_gotypes.go:610 +0x50
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueReadBuffer.func1(0x46373b0, 0x4756960, 0x1, 0x0, 0x8, 0xc420075a40, 0x0, 0x0, 0xc42008c088, 0xc42003c870)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:118 +0x1ff
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueReadBuffer(0xc4200141f0, 0xc420075910, 0xc42008c001, 0x0, 0x8, 0xc420075a40, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:118 +0xea
github.com/robvanmieghem/go-opencl/cl.(*CommandQueue).EnqueueReadBufferByte(0xc4200141f0, 0xc420075910, 0xc42003c901, 0x0, 0xc420075a40, 0x8, 0x8, 0x0, 0x0, 0x0, ...)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/go-opencl/cl/queue.go:125 +0x9c
github.com/robvanmieghem/gominer/algorithms/sia.(*singleDeviceMiner).mine(0xc42007c640)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:182 +0x16d9
created by github.com/robvanmieghem/gominer/algorithms/sia.(*Miner).Mine
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/algorithms/sia/miner.go:56 +0x1ea

goroutine 4 [IO wait]:
net.runtime_pollWait(0xb397f00, 0x72, 0x5)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42005c0d8, 0x72, 0x43cd400, 0x43ca458)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42005c0d8, 0xc42013e000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42005c070, 0xc42013e000, 0x1000, 0x1000, 0x0, 0x43cd400, 0x43ca458)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e040, 0xc42013e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
bufio.(*Reader).fill(0xc42005bec0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42005bec0, 0xa, 0xc420022650, 0xc420022600, 0xc4200684e0, 0xc420134040, 0xc420022600)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadBytes(0xc42005bec0, 0x1000000040cd50a, 0xc4200aefc0, 0x4247780, 0xc420160000, 0x0, 0xc420100060)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:416 +0x66
bufio.(*Reader).ReadString(0xc42005bec0, 0xa, 0x4252380, 0xc4200758b9, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:456 +0x38
github.com/robvanmieghem/gominer/clients/stratum.(*Client).Listen(0xc420100040)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:129 +0xd8
created by github.com/robvanmieghem/gominer/clients/stratum.(*Client).Dial
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:66 +0xdc

goroutine 5 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/time.go:59 +0xf9
github.com/robvanmieghem/gominer/clients/stratum.(*Client).Call.func1(0xc420100040, 0x42b81f1, 0x10, 0xc420014230, 0x1, 0x1, 0x1)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:188 +0x30
created by github.com/robvanmieghem/gominer/clients/stratum.(*Client).Call
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:190 +0x370

goroutine 50 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/time.go:59 +0xf9
github.com/robvanmieghem/gominer/clients/stratum.(*Client).Call.func1(0xc420100040, 0x42b81e1, 0x10, 0xc42015a000, 0x2, 0x2, 0x2)
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:188 +0x30
created by github.com/robvanmieghem/gominer/clients/stratum.(*Client).Call
	/Users/wangchao/source/go/src/github.com/robvanmieghem/gominer/clients/stratum/stratum.go:190 +0x370

rax    0x0
rbx    0x70000072e000
rcx    0x70000072d798
rdx    0x0
rdi    0x2703
rsi    0x6
rbp    0x70000072d7d0
rsp    0x70000072d798
r8     0x70000072d5a0
r9     0x10
r10    0x0
r11    0x206
r12    0x2703
r13    0x70000072da50
r14    0x6
r15    0x2d
rip    0x7fff6f107e3e
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by remotelyliving** [comment]
Try lowering the intensity, worked for me!

**Comment by tlightsky** [comment]
@remotelyliving thanks, i'll try that

**Comment by robvanmieghem** [comment]
@tlightsky can I close this issue?

**Comment by tlightsky** [comment]
@robvanmieghem sure
